### ISSUE TITLE
segmentation fault when running the run-me.sh example

### ISSUE THREAD

**Issue by roeeaharoni** [marian-nmt/marian#84]
Hi,

After compiling the latest version I get a segmentation fault when running the run-me.sh example script.

Specifically, it fails when trying to run the training executable:
`./run-me.sh: line 66: 15469 Segmentation fault      (core dumped) ../../build/marian --model model/model.npz --devices $GPUS --seed 0 --train-sets data/corpus.bpe.ro data/corpus.bpe.en --vocabs model/vocab.ro.yml model/vocab.en.yml --dim-vocabs 66000 50000 --dynamic-batching -w 3000 --layer-normalization --dropout-rnn 0.2 --dropout-src 0.1 --dropout-trg 0.1 --early-stopping 5 --moving-average --valid-freq 10000 --save-freq 10000 --disp-freq 1000 --valid-sets data/newsdev2016.bpe.ro data/newsdev2016.bpe.en --valid-metrics cross-entropy valid-script --valid-script-path ./scripts/validate.sh --log model/train.log --valid-log model/valid.log`

Running the marian executable without any parameters works fine (displaying the different options).

Any idea on how to approach this?

**Comment by emjotde** [comment]
Give me a second. I messed up and fixing things now.

**Comment by emjotde** [comment]
Can you give me the commit hash? I did a number of updates and got confused myself.

**Comment by roeeaharoni** [comment]
94b7d415ebf38909fbce733e57dbf35c20f2005f

**Comment by emjotde** [comment]
It seems to work fine for me, at what point does this happen? Did it train a bit, or does this happen right way? How much RAM does your GPU have?

**Comment by roeeaharoni** [comment]
Happened right away, and I use a TitanX with 12gb. Maybe it has something
to do with the fact that I use boost 1.53?

**Comment by emjotde** [comment]
Hm, that's difficult to assess. I never tested with boost below 1.58. What distribution and version is this?

**Comment by emjotde** [comment]
Hm, just compiled with boost 1.53, works too. What g++ compiler version do you use? Can you post the output of:

```
ls -lah data
ls -lah model
```

Maybe something failed on the way and we have bad error reporting.

**Comment by roeeaharoni** [comment]
g++ --version
g++ (GCC) 6.2.1 20160916 (Red Hat 6.2.1-3)

 **ls -lah data**
total 1.7G
drwxr-xr-x 2 aharonr6 nlp 4.0K Jun 21 17:09 .
drwxr-xr-x 7 aharonr6 nlp 4.0K Jun 21 17:09 ..
-rw-r--r-- 1 aharonr6 nlp    0 Jun 21 16:55 corpus.bpe.en
-rw-r--r-- 1 aharonr6 nlp    0 Jun 21 16:55 corpus.bpe.ro
-rw-r--r-- 1 aharonr6 nlp 223M Apr  6  2016 corpus.bt.ro-en.en
-rw-r--r-- 1 aharonr6 nlp 265M Apr  6  2016 corpus.bt.ro-en.ro
-rw-r--r-- 1 aharonr6 nlp 305M Jun 21 17:09 corpus.en
-rw-r--r-- 1 aharonr6 nlp 359M Jun 21 17:09 corpus.ro
-rw-r--r-- 1 aharonr6 nlp    0 Jun 21 16:55 corpus.tc.en
-rw-r--r-- 1 aharonr6 nlp    0 Jun 21 16:55 corpus.tc.ro
-rw-r--r-- 1 aharonr6 nlp    0 Jun 21 16:55 corpus.tok.clean.en
-rw-r--r-- 1 aharonr6 nlp    0 Jun 21 16:55 corpus.tok.clean.ro
-rw-r--r-- 1 aharonr6 nlp 322M Jun 21 16:55 corpus.tok.en
-rw-r--r-- 1 aharonr6 nlp    0 Jun 21 16:51 corpus.tok.ro
-rw-r--r-- 1 aharonr6 nlp  56M May 15  2012 europarl-v7.ro-en.en
-rw-r--r-- 1 aharonr6 nlp  64M May 15  2012 europarl-v7.ro-en.ro
-rw-r--r-- 1 aharonr6 nlp 777K Jun 21 16:55 newsdev2016.bpe.en
-rw-r--r-- 1 aharonr6 nlp    0 Jun 21 16:55 newsdev2016.bpe.ro
-rw-r--r-- 1 aharonr6 nlp    0 Jun 21 17:09 newsdev2016.bpe.ro.output.postprocessed
-rw-r--r-- 1 aharonr6 nlp 254K Jun 21 15:58 newsdev2016.en
-rw-r--r-- 1 aharonr6 nlp 284K Jun 21 15:58 newsdev2016.ro
-rw-r--r-- 1 aharonr6 nlp 269K Jun 21 16:55 newsdev2016.tc.en
-rw-r--r-- 1 aharonr6 nlp    0 Jun 21 16:55 newsdev2016.tc.ro
-rw-r--r-- 1 aharonr6 nlp 269K Jun 21 16:55 newsdev2016.tok.en
-rw-r--r-- 1 aharonr6 nlp    0 Jun 21 16:55 newsdev2016.tok.ro
-rw-r--r-- 1 aharonr6 nlp 739K Jun 21 16:55 newstest2016.bpe.en
-rw-r--r-- 1 aharonr6 nlp    0 Jun 21 16:55 newstest2016.bpe.ro
-rw-r--r-- 1 aharonr6 nlp    0 Jun 21 17:09 newstest2016.bpe.ro.output.postprocessed
-rw-r--r-- 1 aharonr6 nlp 243K Jun 21 15:58 newstest2016.en
-rw-r--r-- 1 aharonr6 nlp 273K Jun 21 15:58 newstest2016.ro
-rw-r--r-- 1 aharonr6 nlp 256K Jun 21 16:55 newstest2016.tc.en
-rw-r--r-- 1 aharonr6 nlp    0 Jun 21 16:55 newstest2016.tc.ro
-rw-r--r-- 1 aharonr6 nlp 256K Jun 21 16:55 newstest2016.tok.en
-rw-r--r-- 1 aharonr6 nlp    0 Jun 21 16:55 newstest2016.tok.ro
-rw-r--r-- 1 aharonr6 nlp  37M May 16  2012 ro-en.tgz
-rw-rw-r-- 1 aharonr6 nlp  27M Jan 20  2016 SETIMES2.en-ro.en
-rw-rw-r-- 1 aharonr6 nlp  13M Jan 20  2016 SETIMES2.en-ro.ids
-rw-rw-r-- 1 aharonr6 nlp  31M Jan 20  2016 SETIMES2.en-ro.ro
-rw-r--r-- 1 aharonr6 nlp  22M Jan 20  2016 SETIMES2.ro-en.txt.zip

**ls -lah model**
total 4.0K
drwxr-xr-x 2 aharonr6 nlp   30 Jun 21 17:09 .
drwxr-xr-x 7 aharonr6 nlp 4.0K Jun 21 17:09 ..
-rw-r--r-- 1 aharonr6 nlp    0 Jun 21 17:09 train.log

**Comment by emjotde** [comment]
There we have it. The training corpus has size zero. We should report this better. Actually I tink we already fixed this in the sister repo `marian-train`. Checking what is going on.

**Comment by emjotde** [comment]
Do you have python 3 installed?

**Comment by roeeaharoni** [comment]
Still crashing with python 3 and all train files looking good :(

`run-me.sh: line 66: 16682 Segmentation fault      (core dumped) ../../build/marian --model model/model.npz --devices $GPUS --seed 0 --train-sets data$
corpus.bpe.ro data/corpus.bpe.en --vocabs model/vocab.ro.yml model/vocab.en.yml --dim-vocabs 66000 50000 --dynamic-batching -w 3000 --layer-normaliza$
ion --dropout-rnn 0.2 --dropout-src 0.1 --dropout-trg 0.1 --early-stopping 5 --moving-average --valid-freq 10000 --save-freq 10000 --disp-freq 1000 -$
valid-sets data/newsdev2016.bpe.ro data/newsdev2016.bpe.en --valid-metrics cross-entropy valid-script --valid-script-path ./scripts/validate.sh --log 
model/train.log --valid-log model/valid.log`

I'll try to re-compile from scratch with boost 1.58.

**Comment by emjotde** [comment]
I still suspect some remnant bad data. Can you again post the output of this? 

Is -lah data model

**Comment by roeeaharoni** [comment]
The current lists:

-rw-r--r-- 1 aharonr6 nlp 353M Jun 26 01:49 corpus.tok.clean.ro
-rw-r--r-- 1 aharonr6 nlp 322M Jun 26 01:47 corpus.tok.en
-rw-r--r-- 1 aharonr6 nlp 357M Jun 26 01:43 corpus.tok.ro
-rw-r--r-- 1 aharonr6 nlp  56M May 15  2012 europarl-v7.ro-en.en
-rw-r--r-- 1 aharonr6 nlp  64M May 15  2012 europarl-v7.ro-en.ro
-rw-r--r-- 1 aharonr6 nlp 276K Jun 26 02:31 newsdev2016.bpe.en
-rw-r--r-- 1 aharonr6 nlp 298K Jun 26 02:31 newsdev2016.bpe.ro
-rw-r--r-- 1 aharonr6 nlp    0 Jun 26 02:31 newsdev2016.bpe.ro.output.postprocessed
-rw-r--r-- 1 aharonr6 nlp 254K Jun 26 01:37 newsdev2016.en
-rw-r--r-- 1 aharonr6 nlp 284K Jun 26 01:37 newsdev2016.ro
-rw-r--r-- 1 aharonr6 nlp 269K Jun 26 02:06 newsdev2016.tc.en
-rw-r--r-- 1 aharonr6 nlp 286K Jun 26 02:06 newsdev2016.tc.ro
-rw-r--r-- 1 aharonr6 nlp 269K Jun 26 01:47 newsdev2016.tok.en
-rw-r--r-- 1 aharonr6 nlp 286K Jun 26 01:47 newsdev2016.tok.ro
-rw-r--r-- 1 aharonr6 nlp 262K Jun 26 02:31 newstest2016.bpe.en
-rw-r--r-- 1 aharonr6 nlp 282K Jun 26 02:31 newstest2016.bpe.ro
-rw-r--r-- 1 aharonr6 nlp    0 Jun 26 02:31 newstest2016.bpe.ro.output.postprocessed
-rw-r--r-- 1 aharonr6 nlp 243K Jun 26 01:37 newstest2016.en
-rw-r--r-- 1 aharonr6 nlp 273K Jun 26 01:37 newstest2016.ro
-rw-r--r-- 1 aharonr6 nlp 256K Jun 26 02:06 newstest2016.tc.en
-rw-r--r-- 1 aharonr6 nlp 273K Jun 26 02:06 newstest2016.tc.ro
-rw-r--r-- 1 aharonr6 nlp 256K Jun 26 01:47 newstest2016.tok.en
-rw-r--r-- 1 aharonr6 nlp 273K Jun 26 01:47 newstest2016.tok.ro
-rw-r--r-- 1 aharonr6 nlp  37M May 16  2012 ro-en.tgz
-rw-rw-r-- 1 aharonr6 nlp  27M Jan 20  2016 SETIMES2.en-ro.en
-rw-rw-r-- 1 aharonr6 nlp  13M Jan 20  2016 SETIMES2.en-ro.ids
-rw-rw-r-- 1 aharonr6 nlp  31M Jan 20  2016 SETIMES2.en-ro.ro
-rw-r--r-- 1 aharonr6 nlp  22M Jan 20  2016 SETIMES2.ro-en.txt.zip

model:
total 15M
drwxr-xr-x 2 aharonr6 nlp  105 Jun 26 01:15 .
drwxr-xr-x 7 aharonr6 nlp 4.0K Jun 26 09:40 ..
-rw-r--r-- 1 aharonr6 nlp 980K Jun 26 02:24 roen.bpe
-rw-r--r-- 1 aharonr6 nlp    0 Jun 26 01:15 train.log
-rw-r--r-- 1 aharonr6 nlp 5.5M Jun 26 01:57 truecase-model.en
-rw-r--r-- 1 aharonr6 nlp 7.8M Jun 26 01:53 truecase-model.ro

**Comment by emjotde** [comment]
Hm. Data seems to be indeed OK. It segfaults right away, not even outputting anything to the logs. That's weird. This is still the same commit version as above?

**Comment by roeeaharoni** [comment]
I'm currently on commit 94b7d415ebf38909fbce733e57dbf35c20f2005f

**Comment by geovedi** [comment]
@roeeaharoni why there're some `$` in your error log, e.g. `data$` after `--train-sets` also `-$` after `--disp-freq 1000`, and `--layer-normaliza$ ion`. bad copy paste?

```run-me.sh: line 66: 16682 Segmentation fault (core dumped) ../../build/marian --model model/model.npz --devices $GPUS --seed 0 --train-sets data$ corpus.bpe.ro data/corpus.bpe.en --vocabs model/vocab.ro.yml model/vocab.en.yml --dim-vocabs 66000 50000 --dynamic-batching -w 3000 --layer-normaliza$ ion --dropout-rnn 0.2 --dropout-src 0.1 --dropout-trg 0.1 --early-stopping 5 --moving-average --valid-freq 10000 --save-freq 10000 --disp-freq 1000 -$ valid-sets data/newsdev2016.bpe.ro data/newsdev2016.bpe.en --valid-metrics cross-entropy valid-script --valid-script-path ./scripts/validate.sh --log model/train.log --valid-log model/valid.log```

**Comment by roeeaharoni** [comment]
@geovedi I copy-pasted the error from the console as-is (after running `bash run-me.sh` in the training dir).

**Comment by emjotde** [comment]
Let's try to reduce complexity, does this segfault?

```
../../build/marian --model model/model.npz --devices 0 --train-sets data/corpus.bpe.ro data/corpus.bpe.en --vocabs model/vocab.ro.yml model/vocab.en.yml --dim-vocabs 66000 50000
```

**Comment by roeeaharoni** [comment]
Yup:
```
../../build/marian --model model/model.npz --devices 0 --train-sets data/corpus.bpe.ro data/corpus.bpe.en --vocabs model/vocab.ro.yml model/vocab.en.yml --dim-vocabs 66000 50000
Segmentation fault (core dumped)

```

**Comment by emjotde** [comment]
Arg. And this:

```
../../build/marian --train-sets data/corpus.bpe.ro data/corpus.bpe.en
```

**Comment by roeeaharoni** [comment]
Still crashes:
`../../build/marian --train-sets data/corpus.bpe.ro data/corpus.bpe.en
Segmentation fault (core dumped)`

**Comment by emjotde** [comment]
can you try the respority `marian-train` instead of `marian` and try current master there?

**Comment by roeeaharoni** [comment]
Will try that now 👍

**Comment by roeeaharoni** [comment]
I get some warnings re. cudnn when running cmake, is it OK?
```
cmake3 -DCUDNN_INCLUDE_DIR=/home/nlp/aharonr6/cuDNN/include/ -DCUDNN_LIBRARIES=/home/nlp/aharonr6/cuDNN/lib64/ ..
-- Found Cudnn_5105 at /home/nlp/aharonr6/cuDNN/include /home/nlp/aharonr6/cuDNN/lib64
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   system
--   timer
--   iostreams
--   filesystem
--   chrono
--   program_options
--   thread
--   regex
--   date_time
--   atomic
-- Configuring done
WARNING: Target "marian_rescorer" requests linking to directory "/home/nlp/aharonr6/cuDNN/lib64".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "marian_translate" requests linking to directory "/home/nlp/aharonr6/cuDNN/lib64".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "marian_train" requests linking to directory "/home/nlp/aharonr6/cuDNN/lib64".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /home/nlp/aharonr6/git/marian-train/build
```

**Comment by emjotde** [comment]
@tomekd What do make out of this CuDNN messages ?

**Comment by geovedi** [comment]
@roeeaharoni try

```cmake3 -DCUDNN_INCLUDE_DIR=/home/nlp/aharonr6/cuDNN/include/ -DCUDNN_LIBRARIES=/home/nlp/aharonr6/cuDNN/lib64/libcudnn.so ..```

**Comment by roeeaharoni** [comment]
@geovedi warnings are gone, thanks!

**Comment by roeeaharoni** [comment]
Now I get:
```
[ 69%] Building NVCC (Device) object src/CMakeFiles/marian.dir/optimizers/marian_generated_optimizers.cu.o
In file included from /usr/local/cuda/include/cuda_runtime.h:78:0,
                 from <command-line>:0:
/usr/local/cuda/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!
```
Running `gcc --version` results in: `gcc (GCC) 6.2.1 20160916 (Red Hat 6.2.1-3)`

**Comment by emjotde** [comment]
Hm. cuda does not like your compiler. I think cuda 8.0 only supports up g++5

**Comment by roeeaharoni** [comment]
I'll try to get it installed. Thanks!

**Comment by emjotde** [comment]
In case CUDNN is giving you more troubles, I disabled it in current master of marian-train until those version issues are resolved.

**Comment by roeeaharoni** [comment]
One more step in the journey to marian:
After installing boost 1.58 and gcc/g++ 5.4 I'm getting many similar errors when running make. For example:
```
CMakeFiles/amun.dir/common/decoder_main.cpp.o: In function `main':
decoder_main.cpp:(.text.startup+0x101b): undefined reference to `boost::timer::format[abi:cxx11](boost::timer::cpu_times const&, short)'
CMakeFiles/libcommon.dir/common/config.cpp.o: In function `void boost::program_options::validate<unsigned long, char>(boost::any&, std::vector<s
td::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits
<char>, std::allocator<char> > > > const&, unsigned long*, long) [clone .constprop.764]':
config.cpp:(.text+0x3e08): undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string
<char, std::char_traits<char>, std::allocator<char> > const&)'

```
```
CMakeFiles/libcommon.dir/common/config.cpp.o:config.cpp:(.text+0x674d): more undefined references to `boost::program_options::abstract_variables
_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const' follow
CMakeFiles/libcommon.dir/common/config.cpp.o: In function `boost::program_options::validation_error::validation_error(boost::program_options::va
lidation_error::kind_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char,
 std::char_traits<char>, std::allocator<char> > const&, int)':
config.cpp:(.text._ZN5boost15program_options16validation_errorC2ENS1_6kind_tERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_i[_ZN5boos
t15program_options16validation_errorC5ENS1_6kind_tERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_i]+0x26): undefined reference to `bo
ost::program_options::validation_error::get_template[abi:cxx11](boost::program_options::validation_error::kind_t)'
config.cpp:(.text._ZN5boost15program_options16validation_errorC2ENS1_6kind_tERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_i[_ZN5boos
t15program_options16validation_errorC5ENS1_6kind_tERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_i]+0x3c): undefined reference to `bo
ost::program_options::error_with_option_name::error_with_option_name(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<cha
r> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_
traits<char>, std::allocator<char> > const&, int)'
```

```
CMakeFiles/libcommon.dir/common/config.cpp.o: In function `boost::program_options::typed_value<bool, char>::xparse(boost::any&, std::vector<std:
:__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<ch
ar>, std::allocator<char> > > > const&) const':
config.cpp:(.text._ZNK5boost15program_options11typed_valueIbcE6xparseERNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES
aISB_EE[_ZNK5boost15program_options11typed_valueIbcE6xparseERNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISB_EE]+0
x17): undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>,
 std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool*, int)'
CMakeFiles/libcommon.dir/common/config.cpp.o: In function `boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits
<char>, std::allocator<char> >, char>::xparse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<c
har> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const':
config.cpp:(.text._ZNK5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcE6xparseERNS_3anyERKSt6vectorIS7
_SaIS7_EE[_ZNK5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcE6xparseERNS_3anyERKSt6vectorIS7_SaIS7_E
E]+0x17): undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<ch
ar>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__c
xx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)'
```

**Comment by hieuhoang** [comment]
i don't believe the python library is needed unless 'libpython'  is compiled. I'm not sure where libboost_python is being linked 'cos but if you find it please let me know

**Comment by emjotde** [comment]
@tomekd Didn't we make the dependency on python optional at one point? Why is this enabled by default now?

**Comment by tomekd** [comment]
I've just look a look into CMake.

We made optional depedency on PythonLib (e.g. python-dev from ubuntu) but I we still require boost python. Hopefully I fix that.

@roeeaharoni : can you check out fixPython branch?

**Comment by roeeaharoni** [comment]
The fixPython branch works! Should I close the issue now or do you want me to try out the master branch after you merge?

**Comment by hieuhoang** [comment]
ya, try master. I've merge already

Hieu Hoang
http://moses-smt.org/

**Comment by hieuhoang** [comment]
Oh, completely unrelated. Ignore prev message

**Comment by emjotde** [comment]
Let's keep this open for a while. I want to find out what is actually going on here.

**Comment by geovedi** [comment]
@tomekd can you make python3 optional too while you working on it? see #74. thanks!

**Comment by emjotde** [comment]
@roeeaharoni So, did this go away in the end? What was the solution?

**Comment by AmitMY** [comment]
@emjotde I'm having the same python problem on master, and I don't want to use the `fixPython` branch as it pretty old by now.
Any chance it gets merged into master?

(Full description:
When running `cmake ..` it gets stuck with a CMake Error: 
>   Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
  (Required is at least version "2.7")

I too am using Anaconda for my python environment)

**Comment by emjotde** [comment]
@snukky Are we still using python libs anywhere?

**Comment by snukky** [comment]
Not in Marian. Amun uses Python.

**Comment by emjotde** [comment]
Ah right. Can we switch off Amun compilaton with a flag?

**Comment by snukky** [comment]
There is no such a flag. Maybe we should add it or (much better) finally separate Marian and Amun.

**Comment by emjotde** [comment]
@snukky We should probably make the exchange before the marathon. Amun will get its own repository and be pulled in if there is a flag set to ON.

**Comment by emjotde** [comment]
If we merge branches correctly, via remote sources, we should be able to preserve all commits etc. without having to move repositories.

**Comment by AmitMY** [comment]
```sh
git clone https://github.com/marian-nmt/marian-dev
cd marian-dev/
mkdir build
cd build
../../cmake/bin/cmake ..
make -j
cd ..
```
Then:
```sh
libs/marian-dev/build/marian -c model/config.yml
```

works! (well, errors out, because my config is bad, but still progress. Thank you very much)

**Comment by emjotde** [comment]
Great. Have fun.
