### ISSUE TITLE
Weird warnings after merge

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian#89]
Getting these warnings after the merge. Seems to compile, but looks scary.

```
/usr/local/cuda/include/thrust/detail/allocator/allocator_traits.inl(110): warning: calling a __host__ function from a __host__ __device__ function is not allowed
          detected during:
            instantiation of "thrust::detail::enable_if<thrust::detail::allocator_traits_detail::has_member_construct2<Alloc, T, Arg1>::value, void>::type thrust::detail::allocator_traits_detail::construct(Alloc &, T *, const Arg1 &) [with Alloc=std::allocator<amunmt::GPU::NthOut>, T=amunmt::GPU::NthOut, Arg1=amunmt::GPU::NthOut]"
(278): here 
            instantiation of "void thrust::detail::allocator_traits<Alloc>::construct(thrust::detail::allocator_traits<Alloc>::allocator_type &, T *, const Arg1 &) [with Alloc=std::allocator<amunmt::GPU::NthOut>, T=amunmt::GPU::NthOut, Arg1=amunmt::GPU::NthOut]"
/usr/local/cuda/include/thrust/detail/allocator/copy_construct_range.inl(54): here
            instantiation of "void thrust::detail::allocator_traits_detail::copy_construct_with_allocator<Allocator, InputType, OutputType>::operator()(Tuple) [with Allocator=std::allocator<amunmt::GPU::NthOut>, InputType=amunmt::GPU::NthOut, OutputType=amunmt::GPU::NthOut, Tuple=thrust::detail::tuple_of_iterator_references<amunmt::GPU::NthOut &, amunmt::GPU::NthOut &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>]"
/usr/local/cuda/include/thrust/detail/function.h(60): here
            instantiation of "Result thrust::detail::wrapped_function<Function, Result>::operator()(const Argument &) const [with Function=thrust::detail::allocator_traits_detail::copy_construct_with_allocator<std::allocator<amunmt::GPU::NthOut>, amunmt::GPU::NthOut, amunmt::GPU::NthOut>, Result=void, Argument=thrust::detail::tuple_of_iterator_references<amunmt::GPU::NthOut &, amunmt::GPU::NthOut &, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>]"
/usr/local/cuda/include/thrust/system/detail/sequential/for_each.h(56): here
            instantiation of "InputIterator thrust::system::detail::sequential::for_each(thrust::system::detail::sequential::execution_policy<DerivedPolicy> &, InputIterator, InputIterator, UnaryFunction) [with DerivedPolicy=thrust::system::cpp::detail::tag, InputIterator=thrust::zip_iterator<thrust::tuple<thrust::detail::normal_iterator<amunmt::GPU::NthOut *>, amunmt::GPU::NthOut *, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>>, UnaryFunction=thrust::detail::allocator_traits_detail::copy_construct_with_allocator<std::allocator<amunmt::GPU::NthOut>, amunmt::GPU::NthOut, amunmt::GPU::NthOut>]"
/usr/local/cuda/include/thrust/detail/for_each.inl(44): here
            [ 2 instantiation contexts not shown ]
            instantiation of "thrust::detail::enable_if<thrust::detail::allocator_traits_detail::needs_copy_construct_via_allocator<Allocator, thrust::detail::pointer_element<Pointer>::type>::value, Pointer>::type thrust::detail::allocator_traits_detail::copy_construct_range(thrust::execution_policy<FromSystem> &, Allocator &, InputIterator, InputIterator, Pointer) [with FromSystem=thrust::system::cpp::detail::tag, Allocator=std::allocator<amunmt::GPU::NthOut>, InputIterator=thrust::detail::normal_iterator<amunmt::GPU::NthOut *>, Pointer=amunmt::GPU::NthOut *]"
/usr/local/cuda/include/thrust/detail/allocator/copy_construct_range.inl(291): here
            instantiation of "Pointer thrust::detail::copy_construct_range(thrust::execution_policy<System> &, Allocator &, InputIterator, InputIterator, Pointer) [with System=thrust::system::cpp::detail::tag, Allocator=std::allocator<amunmt::GPU::NthOut>, InputIterator=thrust::detail::normal_iterator<amunmt::GPU::NthOut *>, Pointer=amunmt::GPU::NthOut *]"
/usr/local/cuda/include/thrust/detail/contiguous_storage.inl(225): here
            instantiation of "thrust::detail::contiguous_storage<T, Alloc>::iterator thrust::detail::contiguous_storage<T, Alloc>::uninitialized_copy(InputIterator, InputIterator, thrust::detail::contiguous_storage<T, Alloc>::iterator) [with T=amunmt::GPU::NthOut, Alloc=std::allocator<amunmt::GPU::NthOut>, InputIterator=thrust::detail::normal_iterator<amunmt::GPU::NthOut *>]"
/usr/local/cuda/include/thrust/detail/vector_base.inl(790): here
            instantiation of "void thrust::detail::vector_base<T, Alloc>::append(thrust::detail::vector_base<T, Alloc>::size_type) [with T=amunmt::GPU::NthOut, Alloc=std::allocator<amunmt::GPU::NthOut>]"
/usr/local/cuda/include/thrust/detail/vector_base.inl(239): here
            instantiation of "void thrust::detail::vector_base<T, Alloc>::resize(thrust::detail::vector_base<T, Alloc>::size_type) [with T=amunmt::GPU::NthOut, Alloc=std::allocator<amunmt::GPU::NthOut>]"
/home/marcinj/Badania/marian/src/amun/gpu/mblas/nth_element.cu(314): here
```

**Comment by hieuhoang** [comment]
I think it's nvcc version dependent 'cos it doesn't happen to me ( V8.0.44). Git pull again & see what happens

**Comment by emjotde** [comment]
same same

**Comment by hieuhoang** [comment]
strange. try now

**Comment by emjotde** [comment]
no change

**Comment by hieuhoang** [comment]
Whats your os and gcc? I'll set up a vm

**Comment by emjotde** [comment]
```
gcc -v
gcc version 5.2.1 20151031 (Ubuntu 5.2.1-23ubuntu1~14.04.2) 

uname -a
Linux fatboy 3.13.0-119-generic #166-Ubuntu SMP Wed May 3 12:18:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by emjotde** [comment]
I'll check on more machines

**Comment by emjotde** [comment]
The same happens for me on Edinburgh's hodor.

**Comment by geovedi** [comment]
got same warning here.

```
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61```

**Comment by hieuhoang** [comment]
seems to be a thrust issue https://github.com/thrust/thrust/issues/741.

Fixed https://github.com/marian-nmt/marian/commit/0cef4393c68b0b56fe59cb9148b4dd0edb39afad

**Comment by emjotde** [comment]
Are the warnings supposed to be gone now? Cos I still see them.

**Comment by hieuhoang** [comment]
ya. they're gone on on hodor (nvcc V8.0.61). They're not on my nvcc V8.0.44. Where is it still having problems? What thrust version is it? Both mine & hodor is
  #define THRUST_VERSION 100803

**Comment by hieuhoang** [comment]
less /usr/local/cuda/include/thrust/version.h

**Comment by hieuhoang** [comment]
sod it. Gonna get rid of thrust device vector in there. More trouble than it's worth

**Comment by emjotde** [comment]
Still happening on fatboy, same thrust version.

**Comment by hieuhoang** [comment]
try now.

**Comment by emjotde** [comment]
No warnings, looks good.
